<?php echo $this->partial( $this->partialsFolder . '/recipe.phtml', $this->recipe ) ?>

<!-- Ingredients -->
<?php if ( count( $this->ingredients ) > 0 ): ?>
	<h3>Ingredients</h3>
	<!-- Ingredient ID's are recipe_id-ingredient_id -->
	<ul>
	<?php foreach( $this->ingredients as $ingredient ): ?>
		<li id="<?php echo "ingredient-" . $ingredient['recipe_id'] . "-" . $ingredient['ingredient_id'] ?>">
			<ul>
				<?php if ( $ingredient['quantity'] > 0 ): ?>
				<li><?php echo $ingredient['quantity'] ?></li>
				<?php endif ?>
				<?php if ( $ingredient['amount'] > 0 ): ?>
				<li><?php echo $ingredient['amount'] ?></li>
				<?php endif ?>
				<?php if ( !empty( $ingredient['measurement'] ) ): ?>
				<li><?php echo $ingredient['measurement_abbr'] ?></li>
				<?php endif ?>
				<li><?php echo $ingredient['name'] ?>
				<?php if ( $this->checkOwner($this->recipe['creator_id'] ) ): ?>
				<a href="<?php echo "/ingredient/edit/recipe_id/" . $ingredient['recipe_id'] . "/ingredient_id/" . $ingredient['ingredient_id'] ?>">Edit</a> | 
				<a href="<?php echo "/ingredient/delete/recipe_id/" . $ingredient['recipe_id'] . "/ingredient_id/" . $ingredient['ingredient_id'] ?>">Delete</a>
				<?php endif ?>
				</li>
			</ul>
		</li>
	<?php endforeach ?>
	</ul>
	<p><a href="<?php echo "/ingredient/new/recipe_id/" . $this->recipe['id'] ?>">Add ingredients</a></p>
<?php else: ?>
	<p>No ingredients, why not <a href="<?php echo "/ingredient/new/recipe_id/" . $this->recipe['id'] ?>">Add one</a></p>
<?php endif ?>
<!-- End of Ingredients -->

<!-- Method Items -->
<?php if ( count( $this->methods ) > 0 ): ?>
	<h3>Method</h3>
	<ol>
	<?php foreach( $this->methods as $method ): ?>
		<li id="<?php echo "method-" . $method['id'] ?>"><?php echo $method['description'] ?>
		<?php if ( $this->checkOwner( $this->recipe['creator_id'] ) ): ?>
		<a href="<?php echo "/method/edit/recipe_id/" . $method['recipe_id'] . "/method_id/" . $method['id'] ?>">Edit</a> | <a href="<?php echo "/method/delete/recipe_id/" . $method['recipe_id'] . "/method_id/" . $method['id'] ?>">Delete</a>
		<?php endif ?>
		</li>
	<?php endforeach ?>
	</ol>
	<p><a href="<?php echo "/method/new/recipe_id/" . $this->recipe['id'] ?>">Add more instructions</a></p>
<?php else: ?>
	<p>Well I can't tell you how to make it, why not add some <a href="<?php echo "/method/new/recipe_id/" . $this->recipe['id'] ?>">Instructions</a></p>
<?php endif ?>
<!-- End of Method Items -->

<?php echo $this->partial( $this->partialsFolder . '/tags.phtml', array( 'tags' => $this->tags, 'creator' => $this->recipe['creator_id'] ) ) ?>
	
<!-- Rating -->
<h3>Rating</h3>
<div><?php $r = new Rating();  if ($r->isRated($this->recipe['id'])) { echo ("This recipe is rated: " . $r->getRating($this->recipe['id']) . " / " . Rating::MAX_RATING); } else { echo ("This recipe is unrated."); } ?></div>

<?php if (($this->loggedIn())&&(! $r->checkIfUserHasRated($this->recipe['id'])) && (! $this->checkOwner($this->recipe['creator_id']))) { echo $r->getRatingForm(); }  ?>

<!-- End of rating -->

<!-- Comments -->

<!-- Define FCKeditor src -->
<script type="text/javascript" src="/public/js/jquery.FCKEditor.js" language="Javascript" charset="utf-8"></script>
<script type="text/javascript">
	$(function(){ 
		$('textarea.fck').fck( {
			path: '/public/fck/',
			toolbar: 'Cookery',
			width: 700
		});
	});
	function commentPage( page )
	{
		$.ajax({
			type: "POST",
			url: "/ajax/getcomments",
			data: "page=" + page + "&recipe_id=" + <?php echo $this->recipe['id'] ?>,
			cache: false,
			success: function(html){
				$('#comments-holder').html( html );
			}
		});

	}
</script>

<h3>Comments</h3>
<a href='#' onclick="commentPage(1); return false;">Clickme</a>
<div id="comments-holder">
</div>

<?php /* if ($this->loggedIn()) { echo $c->getCommentForm(); } */ ?>
