	
		<li id="<?php echo "ingredient-" . $this->recipe_id . "-" . $this->ingredient_id ?>">
			<ul>
				<?php $creator_id = $this->getHelper('Partial')->view->recipe['user_id']; ?>
				<?php if( $this->checkOwner($creator_id) ): ?>
				<li class="ingredients">
					<a href="<?= $this->url( array( 
						'controller'    => 'ingredient', 
						'action'        => 'edit',
						'recipe_id'     => $this->recipe_id,
						'ingredient_id' => $this->ingredient_id
					), 'default' ); ?>"><img title="Edit" src="/images/icons/pencil.png" alt="Edit"/></a>&nbsp; 
					<a href="<?= $this->url( array( 
						'controller'    => 'ingredient', 
						'action'        => 'delete',
						'recipe_id'     => $this->recipe_id,
						'ingredient_id' => $this->ingredient_id
					), 'default', true ); ?>"><img title="Delete" src="/images/icons/cross.png" alt="Delete"/></a>
			</li>
				<?php endif ?>
				<?php if ( $this->quantity > 0 ): ?>
				<li class="ingredients"><?php echo $this->quantity ?></li>
				<?php endif ?>
				<?php if ( $this->amount > 0 ): ?>
				<li class="ingredients"><?php echo $this->amount ?></li>
				<?php endif ?>
				<?php if ( !empty( $this->measurement ) ): ?>
				<li class="ingredients"><?php echo $this->measurement ?></li>
				<?php endif ?>
				<li class="ingredients"><?php echo $this->name ?></li>
				
			</ul>
		</li>

