<div>
	<h2>
		<a href="<?php echo $this->url( array( 
			'controller' => 'recipe', 
			'action' => 'view',
			'id'     => $this->id
		), 'default' ); ?>"><?php echo $this->escape( $this->name ) . ' ' . round_brackets( $this->view_count ) ?>
		</a></h2>
	<h3>By 
		<a href="<?php echo $this->url( array(
			'controller' => 'recipe',
			'action' => 'user',
			'user_id' => strtolower($this->username)
		), 'default' ); ?>"><?php echo $this->username ?></a>
	</h3>
	<div>
		<ul id="recipe-summary">
			<li><?php echo 'Difficulty: ' . $this->difficulty ?></li>
			<li><?php echo 'Serves: ' . $this->serves ?></li>
			<li><?php echo 'Cooking Time: ' . $this->cooking_time ?></li>
			<li><?php echo 'Preparation Time: ' . $this->preparation_time ?></li>
			<li><?php echo 'No of Ingredients: ' . $this->ingredients_count ?></li>
			<!-- <li><?php echo 'Ratings count: ' . $this->ratings_count ?></li> -->
			<li><?php echo 'Comments count: ' . $this->comments_count ?></li>
			<?php echo ( $this->freezable ? '<li>Freezable</li>' : null ) ?>
		</ul>
	</div>
	<!-- Edit/Delete links  -->
	<div>
		<a href="<?= $this->url( array( 
			'controller' => 'recipe', 
			'action' => 'edit',
			'id'     => $this->id
		), 'default' ); ?>">Edit</a> | 
		<a href="<?= $this->url( array( 
			'controller' => 'recipe', 
			'action' => 'delete',
			'id'     => $this->id
		), 'default' ); ?>">Delete</a>
	</div>
</div>
