<div>
	<h2><?php echo $this->user['name'] ?></h2>
	
	<div><?php echo $this->form ?></div>
	
	<div>
		<h3>Stats</h3>
		<ul>
			<li>Created : <?php echo $this->user['created'] ?></li>
			<li>Updated : <?php echo $this->user['updated'] ?></li>
			<li>No of Recipes : <?php echo $this->recipes_count ?></li>
			<li>Comments Left : <?php echo $this->user['comments_count'] ?></li>
			<li>Ratings Left : <?php echo $this->user['ratings_count'] ?></li>
			<li>Avg Rating : <?php ?></li>
		</ul>
	</div>
</div>