	<h2><?php echo $this->name . ' ' . round_brackets( $this->view_count ) ?></h2>
	<div>
		<ul>
			<li><?php echo 'Difficulty: ' . $this->difficulty ?></li>
			<li><?php echo 'No of Ingredients: ' . $this->ingredients_count ?></li>
			<li><?php echo 'Ratings count: ' . $this->ratings_count ?></li>
			<li><?php echo 'Comments count: ' . $this->comments_count ?></li>
			<li><?php echo ( $this->freezable ? 'Freezable' : '' ) ?></li>
		</ul>
	</div>
	<div>Added by :
	<?php if ( $this->checkOwner( $this->creator_id ) ): ?>
	You
	<?php else: ?>
	<a href="<?php echo '/recipe/index/user_id/' . $this->user->id ?>"><?php echo $this->user->name ?></a>
	<?php endif ?>
	<?php echo $this->created ?>
	on <?php echo date( 'd-M-Y H:i:s', strtotime( $this->created ) ) ?>
	updated <?php echo date( 'd-M-Y H:i:s', strtotime( $this->updated ) ) ?>
	</div>
	<div>
		<?php if ( $this->getHelper('Partial')->view->action != 'view' && $this->getHelper('Partial')->view->controller == 'recipe' ): ?>
		<a href="<?php echo "/recipe/view/recipe_id/".$this->id ?>">View</a>
		<?php endif ?>
<?php if ( $this->checkOwner( $this->creator_id ) ): ?>
		<a href="<?php echo "/recipe/edit/recipe_id/".$this->id ?>">Edit</a>
		<a href="<?php echo "/recipe/delete/recipe_id/".$this->id ?>">Delete</a>
<?php endif ?>
	</div>

