	<h2><?php echo $this->escape( $this->name ) . ' ' . round_brackets( $this->view_count ) ?></h2>
	<div>
		<ul id="recipe-summary">
			<li><?php echo 'Difficulty: ' . $this->difficulty ?></li>
			<li><?php echo 'Serves: ' . $this->serves ?></li>
			<li><?php echo 'Cooking Time: ' . $this->cooking_time ?></li>
			<li><?php echo 'Preparation Time: ' . $this->preparation_time ?></li>
			<li><?php echo 'No of Ingredients: ' . $this->ingredients_count ?></li>
			<li><?php echo 'Ratings count: ' . $this->ratings_count ?></li>
			<li><?php echo 'Comments count: ' . $this->comments_count ?></li>
			<?php echo ( $this->freezable ? '<li>Freezable</li>' : null ) ?>
		</ul>
	</div>

