<!-- Tags -->
<?php if ( count( $this->tags ) > 0 ): ?>
	<h3>Tags</h3>
	<div>
		<ol>
			<?php foreach ($this->tags as $tag): ?>	
			<li>
				<a href="<?php echo "/tag/name/".$tag['name'] ?>"><?php echo $tag['name'] ?></a>
				<?php if ( $this->loggedIn() && $this->checkOwner( $this->creator ) ): ?>
				<a href="<?php echo "/tag/delete/tagging_id/".$tag['id'] ?>">x</a>	
				<?php endif ?>
			</li>
			<?php endforeach ?>
		</ol>
	</div>
<?php endif ?>
<!-- End of Tags -->
