<?= $this->doctype() ?> <!-- This Line will output the doctype we set inside the bootstrap file -->
<html xmlns="http://www.w3.org/1999/xhtml"> 
<head>  
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" /> 
	<title><?php echo $this->title ?></title>
	<!--
	  The line below demonstrates usage of the headLink() view helper
	  @see http://framework.zend.com/manual/en/zend.view.helpers.html
	-->
	<?php $this->headLink()->appendStylesheet('/css/recipe.css') ?>

	<!-- // @todo Maybe move these to a Jquery include -->
	<?php 
		$this->headLink()->appendStylesheet('/js/markitup/skins/markitup/style.css');
		$this->headLink()->appendStylesheet('/js/markitup/sets/default/style.css');
		$this->headLink()->appendStylesheet('/css/jquery-ui-1.7.2.custom.css');
		echo $this->headLink()->appendStylesheet('/css/jquery.autocomplete.css');
		
		$this->headScript()->appendFile('/js/functions.js');
		$this->headScript()->appendFile('/js/jquery-1.3.2.min.js');
		$this->headScript()->appendFile('/js/jquery-ui-1.7.2.custom.min.js');
		$this->headScript()->appendFile('/js/jquery.autocomplete.pack.js');
		 
		// RTF editor in jquery
		$this->headScript()->appendFile('/js/markitup/jquery.markitup.js');
		echo $this->headScript()->appendFile('/js/markitup/sets/default/set.js');
	?>
	
	<script type="text/javascript" >
		$(document).ready(function() {
			$(".richedit").markItUp(mySettings);
		});
	</script>

</head> 
<body>

	<!-- Messages to users -->
	<div>
		<div id="notice" class="notice">
		<?php foreach( $this->message->getMessages() as $msg ): ?>
			<?php echo $msg; ?>
		<?php endforeach ?>
		</div>

		<?php $this->message->setNameSpace('error') ?>
		<div id="error" class="error">
		<?php foreach( $this->message->getMessages() as $msg ): ?>
			<?php echo $msg; ?>
		<?php endforeach ?>
		</div>
	</div>
	<!-- end Messages to users -->
	
	<?php echo $this->render( $this->includesFolder . '/user_details.php') ?>
	
	<!-- Navigation -->
	<div id="menu">
	<ul>
		<li><h2><a href="/">Home</a></h2></li>
	</ul>
	<ul>
	<?php if ( $this->identity ): ?>
		<li><h2>You</h2>
		<ul>
			<li><a href="/user/account">My Account</a></li>	
			<li><a href="<?php echo '/recipe/user/user_id/'.strtolower($this->identity['name']) ?>">My Recipes</a></li>	
			<li><a href="<?php echo $this->url( array( 
			'controller' => 'recipe', 
			'action' => 'new',
		), 'default' ); ?>">New Recipe</a></li>
		</ul></li>
	<?php else: ?>
		<li><h2><a href="/login/">Login</a> / <a href="/user/new">Register</a></h2></li>
	<?php endif ?>
	</ul>
	<ul>
		<li><h2><a href="http://cookingwithzend.blogspot.com/">Blog</a></h2></li>
	</ul>
	</div>
	<!-- End Navigation -->

<!-- This next call will now include any content that was generated in the
     dispatching of a controllers action (or series of actions).  -->
<?= $this->layout()->content ?>

<!-- if your application requires it, this would be a great place to put a
     footer for all pages. -->

</body>
</html>
