<?php echo $this->partial( $this->partialsFolder . '/recipe.phtml', $this->recipe ) ?>

<!-- Ingredients -->
<?php if ( count( $this->recipe['ingredients_count'] ) > 0 ): ?>
	<h3>Ingredients</h3>
	<p><a href="<?php echo "/ingredient/new/recipe_id/" . $this->recipe['id'] ?>">Add another ingredient?</a></p>
<?php else: ?>
	<p>No ingredients, why not <a href="<?php echo "/ingredient/new/recipe_id/" . $this->recipe['id'] ?>">Add one</a></p>
<?php endif ?>
<!-- End of Ingredients -->
2