<div>
	<?php echo $this->partial( $this->partialsFolder . '/recipe.phtml', $this->recipe ) ?>
 
	<!-- Ingredients -->
	<div>
		<div>
			<h3>Ingredients</h3>
			<ul>
			<?php foreach ($this->ingredients as $ingredient ): ?>
			<?php echo $this->partial( $this->partialsFolder . '/ingredient.phtml', $ingredient ); ?>
			<?php endforeach; ?>
			</ul>
		</div>
		<div>	
			<p><a href="<?= $this->url( array( 
				'controller' => 'ingredient', 
				'action' => 'new',
				'recipe_id' => $this->recipe['id']
			), 'default', true ); ?>">
			Add another ingredient?</a></p>
		</div>
	</div>
	<!-- End of Ingredients -->
	
	<!-- Methods -->
	<a name="methods"></a>
	<div>
		<h3>Method</h3>
		<ol>
	<?php foreach ($this->methods as $method): ?>
			<li><?php echo $this->escape( $method['description'] ); ?>
			<a href="<?= $this->url( array( 
				'controller' => 'method', 
				'action' => 'edit',
				'id' => $method['id']
			), 'default', true ); ?>">Edit</a>
			|
			<a href="<?= $this->url( array( 
				'controller' => 'method', 
				'action' => 'delete',
				'id' => $method['id']
			), 'default', true ); ?>">Delete</a>
			</li>
	<?php endforeach; ?>
		</ol>
		<div>
			<p><a href="<?= $this->url( array( 
				'controller' => 'method', 
				'action' => 'new',
				'recipe_id' => $this->recipe['id']
			), 'default', true ); ?>">
			Add another method?</a></p>
		</div>
	</div>
	
	<!-- Comments -->
	<a name="comments"></a>
	<div>
		<h3>Comments</h3>
		<?php echo $this->form ?>
		<?php foreach ($this->comments as $comment): ?>
		<div>
			<?php echo $comment['comment'] ?> by
			<a href="<?= $this->url( array( 
				'controller' => 'user', 
				'action' => 'view',
				'id' => strtolower($comment['username'])
			), 'default', true ); ?>"><?php echo $comment['username']; ?></a>
			<small><?php echo $comment['created'] ?></small>
		</div>
		<?php endforeach; ?>
	</div>
</div>