<script type="text/javascript">
$(function(){
	$('.auto-submit-star').rating();
});
</script>

<?php foreach( $this->recipes as $recipe ): ?>
<div style="border: dashed 2px black;margin-bottom: 10px;">
	<?php echo $this->partial( 'partials/recipe.phtml', $recipe ) ?>

	<?php echo $this->partial( 'partials/tags.phtml', array( 'tags' => $recipe['tags'], 'creator' => $recipe['creator_id'] ) ) ?>

	<div><?php echo $this->starRating( $recipe['rating'] ); ?></div>
</div>
<?php endforeach ?>

