<script type="text/javascript">
$(function(){
	$('.auto-submit-star').rating();
});
</script>

<?php foreach( $this->recipes as $recipe ): ?>
<div style="border: solid 2px black;margin-bottom: 10px;">

	<?php echo $this->partial( $this->partialsFolder . '/recipe.phtml', $recipe ) ?>

	<?php //echo $this->partial( $this->partialsFolder . '/tags.phtml', array( 'tags' => $recipe['tags'], 'creator' => $recipe['creator_id'] ) ) ?>

	<div><?php //echo $this->starRating( $recipe['rating'] ); ?></div>
</div>
<?php endforeach ?>

