<?php if (count($this->paginator)): ?>
<?php foreach ($this->paginator as $recipe): ?>
<div style="border-bottom: solid 2px black;margin-bottom: 10px;">

	<?php echo $this->partial( $this->partialsFolder . '/recipe.phtml', $recipe ) ?>

	<?php //echo $this->partial( $this->partialsFolder . '/tags.phtml', array( 'tags' => $recipe['tags'], 'creator' => $recipe['user_id'] ) ) ?>

	<div><?php //echo $this->starRating( $recipe['rating'] ); ?></div>
</div>
<?php endforeach; ?>
</ul>
<?php endif; ?>

<?php echo $this->paginationControl($this->paginator, 'Sliding', 'includes/pagination.php'); ?>
