<script type="text/javascript">
$().ready(function(){
	$("#ingredient-name").autocomplete("/ajax/getingredients", {
		parse: function(data) {
			return $.map(eval(data), function(row) {
				return {
					data: row,
					value: row.id,
					result: row.name
				}
			});
		},
		formatItem: function(item) {
			return item.name;
		}
	});
	$("#measurement-name").autocomplete("/ajax/getmeasurements", {
		parse: function(data) {
			return $.map(eval(data), function(row) {
				return {
					data: row,
					value: row.id,
					result: row.name
				}
			});
		},
		formatItem: function(item) {
			return item.name + " (" + item.abbreviation + ")";
		}
	});

});
</script>

<ul>
	<li><a href="<?php echo "/recipe/view/recipe_id/".$this->recipe_id; ?>">Back to Recipe</a></li>
</ul>

<ul>
	<?php if ( $this->ingredients ): ?>
	<?php echo $this->partialLoop( $this->partialsFolder . '/ingredient.phtml', $this->ingredients ); ?>
	<?php endif ?>
</ul>

<?php echo $this->form ?>
